//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: binToInt.java
//

#ifndef _BinToInt_H_
#define _BinToInt_H_

#include "J2ObjC_header.h"

@class IOSIntArray;
@class IOSObjectArray;

@interface binToInt : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)mainWithNSStringArray:(IOSObjectArray *)args;

#pragma mark Package-Private

+ (void)initBinWithIntArray:(IOSIntArray *)binToInt OBJC_METHOD_FAMILY_NONE;

+ (void)inputBinWithIntArray:(IOSIntArray *)binToInt;

+ (void)outputIntWithIntArray:(IOSIntArray *)binToInt;

@end

J2OBJC_EMPTY_STATIC_INIT(binToInt)

FOUNDATION_EXPORT void binToInt_mainWithNSStringArray_(IOSObjectArray *args);

FOUNDATION_EXPORT void binToInt_initBinWithIntArray_(IOSIntArray *binToInt);

FOUNDATION_EXPORT void binToInt_inputBinWithIntArray_(IOSIntArray *binToInt);

FOUNDATION_EXPORT void binToInt_outputIntWithIntArray_(IOSIntArray *binToInt);

FOUNDATION_EXPORT void binToInt_init(binToInt *self);

FOUNDATION_EXPORT binToInt *new_binToInt_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(binToInt)

@compatibility_alias BinToInt binToInt;

#endif // _BinToInt_H_
